services:
  next:
    container_name: next
    build: .
    image: fullstack/frontend
    volumes:
      - next-volume:/var/www/html

  nginx: 
    container_name: nginx
    build: ./nginx
    image: fullstack/nginx
    networks:
      - fullstack-network
    ports:
      - 80:80
    volumes:
      - next-volume:/var/www/html
    depends_on:
      - next

networks:
  fullstack-network:
    name: fullstack-network
    external: true

volumes:
  next-volume: